import '@/styles/reset.css';
import '@/styles/globals.css';
import '@/styles/index.css';
import { Inter } from 'next/font/google';
import { ApolloWrapper } from '../lib/apollo-wrapper';
import ThemeWrapper from '@/lib/theme-wrapper';
import ActiveCustomerWrapper from '@/lib/active-customer-wrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="wrapper">
          <ApolloWrapper>
            <ThemeWrapper>
              <ActiveCustomerWrapper>{children}</ActiveCustomerWrapper>
            </ThemeWrapper>
          </ApolloWrapper>
        </main>
      </body>
    </html>
  );
}
